# Generated by Django 4.2 on 2023-04-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_category_slug_blogcategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='slug',
            new_name='subcategory_slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_slug',
        ),
    ]
