# Generated by Django 4.2 on 2023-04-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_slug_subcategory_subcategory_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory_slug',
            new_name='slug',
        ),
    ]
