# Generated by Django 4.2 on 2023-04-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
    ]
