# Generated by Django 4.2 on 2023-04-24 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_remove_post_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='last_post_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='last_post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='last_post_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
