# Generated by Django 4.2 on 2023-04-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_subcategory_last_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='last_post_author',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='last_post_date',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='last_post_title',
        ),
    ]
