# Generated by Django 4.2 on 2023-04-24 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_subcategory_last_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.blogcategory'),
        ),
    ]
