# Generated by Django 4.2 on 2023-04-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_post_category_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_main',
        ),
    ]
