# Generated by Django 4.2 on 2023-04-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_country_options_alter_author_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_photo',
            field=models.ImageField(blank=True, default='static/main/img/profile_icon.png', help_text='Фото профиля', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
