# Generated by Django 4.2 on 2023-04-26 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_author_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('user_name',), 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
