# Generated by Django 4.2 on 2023-04-27 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_author_following_delete_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='following',
        ),
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
