# Generated by Django 4.2 on 2023-05-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_author_followers_author_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
